import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "./components/global/Navbar";
import Footer from "./components/global/Footer";
import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <NavbarComponent /> */}
        <NextUIProvider>
          <NavbarComponent />
          {children}
          <Footer />
        </NextUIProvider>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
